services:
  streamMax-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://streamMax-db:27017/streamMax
    depends_on:
      - streamMax-db

  streamMax-db:
    image: mongo:4.4
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=streamMax
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    name: ecommerce-mongodb-data
