name: CI/CD with GHCR and DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image to GHCR
        env:
          IMAGE_TAG: latest
          CONTAINER_REGISTRY: ghcr.io
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login $CONTAINER_REGISTRY -u $GITHUB_ACTOR --password-stdin
          docker buildx create --use
          docker buildx build --platform linux/amd64 --tag ghcr.io/jay-bhogayata/api-stream-max:latest .
          docker push ghcr.io/jay-bhogayata/api-stream-max:latest

      - name: Deploy application on droplet
        env:
          DIGITALOCEAN_IP: 64.227.186.1
          DIGITALOCEAN_PATH: /root/video_straming_system
        run: |
          echo "${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$DIGITALOCEAN_IP ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABA...your_ssh_public_key_here... " >> ~/.ssh/known_hosts
          ssh-add ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -o ControlMaster=yes -o ControlPersist=yes -o ControlPath=/tmp/ssh-%C.sock root@$DIGITALOCEAN_IP "cd $DIGITALOCEAN_PATH && docker-compose pull && docker-compose down && docker-compose up -d"
